version: 0.2
env:
  variables:
    S3_BUCKET: investors-deeptrack-io-frontend-eu-west-1
    CF_DIST_ID: E3JP1T0XSJ1O0M
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist/ s3://${S3_BUCKET}/ --delete
      - aws cloudfront create-invalidation --distribution-id ${CF_DIST_ID} --paths "/*"
