version: 0.2

env:
  variables:
    S3_BUCKET: investors-deeptrack-io-frontend-eu-west-1
    CF_DIST_ID: E3JP1T0XSJ1O0M
    AWS_REGION: eu-west-1
    NODE_ENV: production
    VITE_AUTH0_DOMAIN: dev-08kwsss3wr77v0k0.us.auth0.com
    VITE_AUTH0_CLIENT_ID: 2nsfWPfcCPkxA3N7Me4aUwjlSsDeoFbM
    VITE_AUTH0_AUDIENCE: https://api.deeptrack.io/data-room
    VITE_AUTH0_ROLE_CLAIM: https://deeptrack.io/roles
    VITE_DATA_ROOM_API_BASE_URL: https://9a8681dr9d.execute-api.eu-west-1.amazonaws.com

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci

  build:
    commands:
      - echo "Building with NODE_ENV=$NODE_ENV"
      - npm run build
      - ls -la dist/

  post_build:
    commands:
      - aws s3 sync dist/ s3://${S3_BUCKET}/ --delete
      - aws cloudfront create-invalidation --distribution-id ${CF_DIST_ID} --paths "/*"
